export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'

export const AUTH_STATUS_SUCCESS = 'AUTH_STATUS_SUCCESS'
export const AUTH_STATUS_FAILED = 'AUTH_STATUS_FAIL'

export const MAIN_RECEIVE_SUMMARY = 'MAIN_RECEIVE_SUMMARY'
export const MAIN_RECEIVE_LINECHART = 'MAIN_RECEIVE_LINECHART'
export const MAIN_LINECHART_DELETED = 'MAIN_LINECHART_DELETED'