const a = {
  type: "ObjectExpression",
  start: 241,
  end: 454,
  loc: { start: { line: 13, column: 2 }, end: { line: 26, column: 3 } },
  extra: { trailingComma: 449 },
  properties: [
    {
      type: "ObjectProperty",
      start: 247,
      end: 258,
      loc: { start: { line: 14, column: 4 }, end: { line: 14, column: 15 } },
      method: false,
      key: {
        type: "Identifier",
        start: 247,
        end: 250,
        loc: {
          start: { line: 14, column: 4 },
          end: { line: 14, column: 7 },
          identifierName: "key",
        },
        name: "key",
      },
      computed: false,
      shorthand: false,
      value: {
        type: "StringLiteral",
        start: 252,
        end: 258,
        loc: { start: { line: 14, column: 9 }, end: { line: 14, column: 15 } },
        extra: { rawValue: "home", raw: "'home'" },
        value: "home",
      },
    },
    {
      type: "ObjectProperty",
      start: 264,
      end: 282,
      loc: { start: { line: 15, column: 4 }, end: { line: 15, column: 22 } },
      method: false,
      key: {
        type: "Identifier",
        start: 264,
        end: 268,
        loc: {
          start: { line: 15, column: 4 },
          end: { line: 15, column: 8 },
          identifierName: "icon",
        },
        name: "icon",
      },
      computed: false,
      shorthand: false,
      value: {
        type: "Identifier",
        start: 270,
        end: 282,
        loc: {
          start: { line: 15, column: 10 },
          end: { line: 15, column: 22 },
          identifierName: "HomeOutlined",
        },
        name: "HomeOutlined",
      },
    },
    {
      type: "ObjectProperty",
      start: 288,
      end: 299,
      loc: { start: { line: 16, column: 4 }, end: { line: 16, column: 15 } },
      method: false,
      key: {
        type: "Identifier",
        start: 288,
        end: 293,
        loc: {
          start: { line: 16, column: 4 },
          end: { line: 16, column: 9 },
          identifierName: "label",
        },
        name: "label",
      },
      computed: false,
      shorthand: false,
      value: {
        type: "StringLiteral",
        start: 295,
        end: 299,
        loc: { start: { line: 16, column: 11 }, end: { line: 16, column: 15 } },
        extra: { rawValue: "首页", raw: "'首页'" },
        value: "首页",
      },
    },
    {
      type: "ObjectProperty",
      start: 305,
      end: 314,
      loc: { start: { line: 17, column: 4 }, end: { line: 17, column: 13 } },
      method: false,
      key: {
        type: "Identifier",
        start: 305,
        end: 309,
        loc: {
          start: { line: 17, column: 4 },
          end: { line: 17, column: 8 },
          identifierName: "path",
        },
        name: "path",
      },
      computed: false,
      shorthand: false,
      value: {
        type: "StringLiteral",
        start: 311,
        end: 314,
        loc: { start: { line: 17, column: 10 }, end: { line: 17, column: 13 } },
        extra: { rawValue: "/", raw: "'/'" },
        value: "/",
      },
    },
    {
      type: "ObjectProperty",
      start: 320,
      end: 449,
      loc: { start: { line: 18, column: 4 }, end: { line: 25, column: 5 } },
      method: false,
      key: {
        type: "Identifier",
        start: 320,
        end: 328,
        loc: {
          start: { line: 18, column: 4 },
          end: { line: 18, column: 12 },
          identifierName: "children",
        },
        name: "children",
      },
      computed: false,
      shorthand: false,
      value: {
        type: "ArrayExpression",
        start: 330,
        end: 449,
        loc: { start: { line: 18, column: 14 }, end: { line: 25, column: 5 } },
        extra: { trailingComma: 442 },
        elements: [
          {
            type: "ObjectExpression",
            start: 338,
            end: 442,
            loc: {
              start: { line: 19, column: 6 },
              end: { line: 24, column: 7 },
            },
            extra: { trailingComma: 433 },
            properties: [
              {
                type: "ObjectProperty",
                start: 348,
                end: 359,
                loc: {
                  start: { line: 20, column: 8 },
                  end: { line: 20, column: 19 },
                },
                method: false,
                key: {
                  type: "Identifier",
                  start: 348,
                  end: 351,
                  loc: {
                    start: { line: 20, column: 8 },
                    end: { line: 20, column: 11 },
                    identifierName: "key",
                  },
                  name: "key",
                },
                computed: false,
                shorthand: false,
                value: {
                  type: "StringLiteral",
                  start: 353,
                  end: 359,
                  loc: {
                    start: { line: 20, column: 13 },
                    end: { line: 20, column: 19 },
                  },
                  extra: { rawValue: "test", raw: "'test'" },
                  value: "test",
                },
              },
              {
                type: "ObjectProperty",
                start: 369,
                end: 387,
                loc: {
                  start: { line: 21, column: 8 },
                  end: { line: 21, column: 26 },
                },
                method: false,
                key: {
                  type: "Identifier",
                  start: 369,
                  end: 373,
                  loc: {
                    start: { line: 21, column: 8 },
                    end: { line: 21, column: 12 },
                    identifierName: "icon",
                  },
                  name: "icon",
                },
                computed: false,
                shorthand: false,
                value: {
                  type: "Identifier",
                  start: 375,
                  end: 387,
                  loc: {
                    start: { line: 21, column: 14 },
                    end: { line: 21, column: 26 },
                    identifierName: "HomeOutlined",
                  },
                  name: "HomeOutlined",
                },
              },
              {
                type: "ObjectProperty",
                start: 397,
                end: 410,
                loc: {
                  start: { line: 22, column: 8 },
                  end: { line: 22, column: 21 },
                },
                method: false,
                key: {
                  type: "Identifier",
                  start: 397,
                  end: 402,
                  loc: {
                    start: { line: 22, column: 8 },
                    end: { line: 22, column: 13 },
                    identifierName: "label",
                  },
                  name: "label",
                },
                computed: false,
                shorthand: false,
                value: {
                  type: "StringLiteral",
                  start: 404,
                  end: 410,
                  loc: {
                    start: { line: 22, column: 15 },
                    end: { line: 22, column: 21 },
                  },
                  extra: { rawValue: "test", raw: "'test'" },
                  value: "test",
                },
              },
              {
                type: "ObjectProperty",
                start: 420,
                end: 433,
                loc: {
                  start: { line: 23, column: 8 },
                  end: { line: 23, column: 21 },
                },
                method: false,
                key: {
                  type: "Identifier",
                  start: 420,
                  end: 424,
                  loc: {
                    start: { line: 23, column: 8 },
                    end: { line: 23, column: 12 },
                    identifierName: "path",
                  },
                  name: "path",
                },
                computed: false,
                shorthand: false,
                value: {
                  type: "StringLiteral",
                  start: 426,
                  end: 433,
                  loc: {
                    start: { line: 23, column: 14 },
                    end: { line: 23, column: 21 },
                  },
                  extra: { rawValue: "/test", raw: "'/test'" },
                  value: "/test",
                },
              },
            ],
          },
        ],
      },
    },
  ],
};
