const a = {
  type: "File",
  start: 0,
  end: 91,
  loc: { start: { line: 1, column: 0 }, end: { line: 6, column: 0 } },
  errors: [],
  program: {
    type: "Program",
    start: 0,
    end: 91,
    loc: { start: { line: 1, column: 0 }, end: { line: 6, column: 0 } },
    sourceType: "module",
    interpreter: null,
    body: [
      {
        type: "ImportDeclaration",
        start: 0,
        end: 37,
        loc: { start: { line: 1, column: 0 }, end: { line: 1, column: 37 } },
        specifiers: [
          {
            type: "ImportSpecifier",
            start: 9,
            end: 15,
            loc: {
              start: { line: 1, column: 9 },
              end: { line: 1, column: 15 },
            },
            imported: {
              type: "Identifier",
              start: 9,
              end: 15,
              loc: {
                start: { line: 1, column: 9 },
                end: { line: 1, column: 15 },
                identifierName: "Button",
              },
              name: "Button",
            },
            importKind: null,
            local: {
              type: "Identifier",
              start: 9,
              end: 15,
              loc: {
                start: { line: 1, column: 9 },
                end: { line: 1, column: 15 },
                identifierName: "Button",
              },
              name: "Button",
            },
          },
          {
            type: "ImportSpecifier",
            start: 17,
            end: 22,
            loc: {
              start: { line: 1, column: 17 },
              end: { line: 1, column: 22 },
            },
            imported: {
              type: "Identifier",
              start: 17,
              end: 22,
              loc: {
                start: { line: 1, column: 17 },
                end: { line: 1, column: 22 },
                identifierName: "Input",
              },
              name: "Input",
            },
            importKind: null,
            local: {
              type: "Identifier",
              start: 17,
              end: 22,
              loc: {
                start: { line: 1, column: 17 },
                end: { line: 1, column: 22 },
                identifierName: "Input",
              },
              name: "Input",
            },
          },
        ],
        importKind: "value",
        source: {
          type: "StringLiteral",
          start: 30,
          end: 36,
          loc: { start: { line: 1, column: 30 }, end: { line: 1, column: 36 } },
          extra: { rawValue: "antd", raw: "'antd'" },
          value: "antd",
        },
      },
      {
        type: "ImportDeclaration",
        start: 38,
        end: 64,
        loc: { start: { line: 2, column: 0 }, end: { line: 2, column: 26 } },
        specifiers: [
          {
            type: "ImportDefaultSpecifier",
            start: 45,
            end: 50,
            loc: {
              start: { line: 2, column: 7 },
              end: { line: 2, column: 12 },
            },
            local: {
              type: "Identifier",
              start: 45,
              end: 50,
              loc: {
                start: { line: 2, column: 7 },
                end: { line: 2, column: 12 },
                identifierName: "react",
              },
              name: "react",
            },
          },
        ],
        importKind: "value",
        source: {
          type: "StringLiteral",
          start: 56,
          end: 63,
          loc: { start: { line: 2, column: 18 }, end: { line: 2, column: 25 } },
          extra: { rawValue: "react", raw: "'react'" },
          value: "react",
        },
      },
      {
        type: "ImportDeclaration",
        start: 65,
        end: 88,
        loc: { start: { line: 3, column: 0 }, end: { line: 3, column: 23 } },
        specifiers: [
          {
            type: "ImportDefaultSpecifier",
            start: 72,
            end: 73,
            loc: { start: { line: 3, column: 7 }, end: { line: 3, column: 8 } },
            local: {
              type: "Identifier",
              start: 72,
              end: 73,
              loc: {
                start: { line: 3, column: 7 },
                end: { line: 3, column: 8 },
                identifierName: "_",
              },
              name: "_",
            },
          },
        ],
        importKind: "value",
        source: {
          type: "StringLiteral",
          start: 79,
          end: 87,
          loc: { start: { line: 3, column: 14 }, end: { line: 3, column: 22 } },
          extra: { rawValue: "lodash", raw: "'lodash'" },
          value: "lodash",
        },
      },
    ],
    directives: [],
  },
  comments: [],
};
